---
version: '3'

services:
  buildserver:
    container_name: buildserver
    image: cv:latest
    build:
      context: .
    volumes:
      - ./dist/:/app/dist/:rw

  webserver:
    container_name: webserver
    image: valerio.dev:latest
    build:
      context: ./config/nginx/
    ports:
      - 8080:80
      - 443:443
    restart: always
    volumes:
      - ./dist/:/usr/share/nginx/html/:ro
      - certs:/etc/letsencrypt:ro
      # - ./config/certbot/:/usr/share/nginx/html/:ro
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://valerio.dev:80/healthcheck"
        ]
      start_period: 5s # Add this line to set a start delay
      interval: 5s
      timeout: 2s
      retries: 3

  certbot:
    container_name: certbot
    depends_on:
      webserver:
        condition: service_healthy
    image: certbot/certbot:latest
    volumes:
      - ./dist/:/usr/share/nginx/html/:rw
      - certs:/etc/letsencrypt:rw
    entrypoint: ["certbot", "certonly", "--webroot", "-w", "/usr/share/nginx/html", "--email", "bruno@valerio.dev", "--agree-tos", "--no-eff-email", "-d", "valerio.dev", "-d", "www.valerio.dev"]

volumes:
  certs: