version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./config/nginx/:/etc/nginx/:ro
      - ./config/nginx/html/:/usr/share/nginx/html/:ro
  certbot:
    depends_on:
      nginx:
        condition: service_healthy
    image: certbot/certbot:latest
    volumes:
      - ./config/certbot/conf/:/etc/letsencrypt/:rw
      - ./config/nginx/html/:/usr/share/nginx/html/:rw
