import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await (await b.newContext()).newPage()
const url = 'file://' + process.cwd() + '/dist/index.html'
await p.setViewportSize({ width: 1280, height: 900 })
await p.goto(url, { waitUntil: 'load' })
await p.evaluate(() => document.fonts.ready)
await p.waitForTimeout(1200)
await p.screenshot({ path: 'proto-top.png' })
await p.evaluate(() => document.querySelector('#experience').scrollIntoView())
await p.waitForTimeout(600)
await p.screenshot({ path: 'proto-rail.png' })
await p.goto(url + '#p1', { waitUntil: 'load' })
await p.evaluate(() => document.fonts.ready)
await p.waitForTimeout(600)
await p.screenshot({ path: 'proto-detail.png' })
await p.setViewportSize({ width: 390, height: 844 })
await p.goto(url, { waitUntil: 'load' })
await p.evaluate(() => document.fonts.ready)
await p.waitForTimeout(1000)
await p.screenshot({ path: 'proto-mobile.png' })
await b.close()
console.log('shots done')
