---
# Disable all linters by default
DEFAULTS:
  DISABLE_ALL: true

# Enable specific linters
ENABLE:
  - YAML
  - JSON
  - MARKDOWN
  - JAVASCRIPT_ES
  - PYTHON_PYLINT

# Optionally, you can configure specific linter rules here
# For example, to configure ESLint:
# JAVASCRIPT_ES:
#   CONFIG_FILE: .eslintrc.json
